# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# This is the minimum version number required.
# Update this, if you use features of a newer version
require 'yaml'
require 'spaceship'
require 'colored'

fastlane_version "1.38.0"

default_platform :ios

class Config
    SLACK_URL = "https://hooks.slack.com/services/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".freeze
    FRAMEWORK_NAME = "SwiftTweaks"
    REPOSITORY_NAME = "SwiftTweaks"
end

module FastlaneHelpers
    module_function

end

extend FastlaneHelpers

platform :ios do
    desc "Release new version"
    lane :release do |options|
        target_version = options[:version]
        raise "The version is missed. Use `fastlane release version:{version_number}`.`" if target_version.nil?
  
        ensure_git_branch
        ensure_git_status_clean
        
        # Increment version
        increment_version_number(version_number: target_version)  
        git_commit_all(message: "Bump version to #{target_version}")
        
        # Create Carthage framework
        Actions.sh("cd.. && carthage build --no-skip-current && carthage archive #{FRAMEWORK_NAME}")
        framework_binary = File.join(File.expand_path('../..', __FILE__),"#{FRAMEWORK_NAME}.framework.zip")
        raise "No binary found to upload" if File.file?(framework_binary)

        # Create release tag
        Actions.sh("git tag -s #{target_version} -m ''")
        push_to_git_remote
        
        set_github_release(
            repository_name: "LootApp/#{REPOSITORY_NAME}",
            api_token: "8ae92e07a31a1409527918e6d88168f44c855e17",
            tag_name: target_version,
            upload_assets: framework_binary.to_s
        )
    end

    error do |lane, exception|
        notification(subtitle: "Fastlane error", message: "Error in lane " + lane.to_s)
    end
end


# More information about multiple platforms in fastlane:
# https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
